### PR TITLE
Adding webmecanik service

### PR DESCRIPTION
**Pull request by Dcoutelle**
Ajout du service webmecanik (marketing automation)

### CODE REVIEW

**Comment by npracht** [comment]
@AmauriC do you think you could merge that ? Our customers are already using it from our fork.
Thanks a lot for your work on that great open source project :)

**Comment by AmauriC** [comment]
Hey, Just need the classic html tag to add it on the doc and approve the merge.

Thanks :+1:

**Comment by npracht** [comment]
Hey @AmauriC, i don't get it. Do i need to give you something else? If yes, what exactly ?
Thanks,

N.

**Comment by GuillaumeKadolis** [comment]
it's not something like this ?

`(tarteaucitron.job = tarteaucitron.job || []).push('webmecanik');`

**Comment by AmauriC** [comment]
How to you currently add webmecanik without tarteaucitron? 

Something like this:
```<script>xxx</script>```

**Comment by npracht** [comment]
@AmauriC here we go !
```js
<script> (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n; w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t), m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m) })(window,document,'script','https://**url**.automation.webmecanik.com/mtc.js','mt'); mt('send', 'pageview'); </script>
```

**Comment by npracht** [comment]
Hello @AmauriC i don't see Webmecanik here https://opt-out.ferank.eu/fr/install/
How could i help to add it there ?

Thanks,

**Comment by AmauriC** [comment]
Done ;)

**Pull request merged**
