### PR TITLE
Select cookie domain

### PR DESCRIPTION
**Pull request by thomascombe**
Allow to select the cookie domain.
To share cookie between all website under the same domain.

### CODE REVIEW

**Comment by AmauriC** [comment]
Don't know if it's gdpr compliant. Any source to confirm that's ok?

As a user if I say "ok" for xxx.xxx.com I don't necessary want to give the same access to yyy.xxx.com

**Comment by thomascombe** [comment]
No source to confirm it.
We say me : if the 2 websites have same "master domain" and the same context, we can use same gdpr cookie.

**Comment by thomascombe** [comment]
@AmauriC For example, a multi-language website with subdomain : en.mywebsite.com - es.mywebsite.com
I think it's gdpr compliant to use the same gdpr cookie because the context is the same ?
Isn't it ?

**Comment by AmauriC** [comment]
+1 for multilingual sites, I did not think about it.

**Comment by vith27** [comment]
Thank for the link to my issue @thomascombe.
Now I have just a question... How to use it ? I saw the explanation with the "init" method, but in case of Drupal module use, I don't see how to implement the cookie domain variable... I tried like the forced language : 
<script type="text/javascript">var tarteaucitronCookieDomain = '*.mydomain.com'</script>
But it doesn't seems to work. And what about the configuration on the https://opt-out.ferank.eu/ admin panel ? We cannot add a wildcard in the domain URL. How it works ?

Thanks in advance for your suggestions.

**Comment by thomascombe** [comment]
I don't think about the Drupal module when I develop this feat.
So it's not possible yet.
I think they have 2 choices : 
1. Update module to allow change this parameter in admin panel
2. Update tarteaucitron.js script to use JS variable like tarteaucitronForceLanguage

**Comment by vith27** [comment]
In my case, we add sub-domains monthly, and if possible, I don't want to manually add each sub-domain on the opt-out.ferank.eu (master) admin panel, but I don't know how I can add only master domain (ie www) and each sub-domain would be linked automatically... It would be great if a wildcard can be used like *.domain.com and any subdomain working with (my.domain.com, another.sub.domain.com, ...). Actually, even if the js is refactored to use a JS variable, I must add each sub-domain manually in the master admin panel.

**Comment by jipexu** [comment]
>As a user if I say "ok" for xxx.xxx.com I don't necessary want to give the same access to yyy.xxx.com

@AmauriC   this is still possible ? or true ?
 because we experimented some problem with this ... so just to known if they belong to a bad config of cookieDomain parameter or not ?... 

if we have a main domain
 www.xxx.com  (cookieDomain parameter must be empty ?)
and  a sub-domain
 yyy.xxx.com (cookieDomain parameter must be yyy.xxx.com ?)

**Pull request merged**
