### PR TITLE
Add Lt Trad

### PR DESCRIPTION
**Pull request by BuyukCem**
Voici la traduciton pour l'issue   "Lithuanian language #651"

### CODE REVIEW

**Comment by AmauriC** [comment]
Awesome, thanks : )

**Comment by Domka** [comment]
hello. thank you for information.  i looked in to website https://tarteaucitron.io/. i cant change into lithuanian language for my project.i dont find it

**Comment by BuyukCem** [comment]
Hello, have you updated the project with "git pull"

**Comment by Domka** [comment]
no, but i am using it from your site https://tarteaucitron.io/ . i am not using WP plugin

**Comment by BuyukCem** [comment]
sorry i didn't understand can you open a issue to help you

**Comment by AmauriC** [comment]
This is not yet embeded on the pro version, I'll add it today or tomorrow ; )

**Pull request merged**
