### PR TITLE
Add New Relic service

### PR DESCRIPTION
**Pull request by Quentinchampenois**
Hello ! This PR creates a new service for [New Relic](https://newrelic.com/).

### Affected cookies
It allows to deal with the New Relic cookies : 
* `JSESSIONID`
* `NREUM`
* `NRAGENT`

### More information
I don't know if I have to add content in the JS function but I don't think so. Let me know if there is missing things.

Thank you !

### CODE REVIEW

**Comment by AmauriC** [comment]
The "js" element is required.

Without it, nothing will be loaded 😕

**Comment by Quentinchampenois** [comment]
Hi, I'm not sure to understand what to do with this element in the New Relic case, because I've tried in local environment and the banner allows to block or accept the target cookies according to the user choice.  

If I understand your feedback, at the moment my service does nothing without this js element ?  

For now I will move this PR to draft, and investigate this js element, thank you for the feedback !

**Comment by AmauriC** [comment]
With tarteaucitron you have to remove from the website the newrelic tag and it will be loaded from tarteaucitron when the user accept it. This is why, on the js section, the new relic code have to be.

Check the others services to see example: https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js

**Comment by Quentinchampenois** [comment]
Thanks for your answer ! 

I will working on it when I can and reopen Pull Request once finished

**Pull request closed without merging**
