### PR TITLE
WIP: [Feature] Add easier development stack

### PR DESCRIPTION
**Pull request by Manoz**
Hey,

As promised I've added a small Gulp stack for easier development and maintenance. I've also made a lot of changes.

Keep in mind that it's a WIP version and we'll have to test everything just in case. Didn't changed that much JS but I changed a lot of CSS.

Here's an overview of what I changed:

## Dev:
1. Added Gulp stack for a more "modern" development approach.

## JavaScript
1. Changes IDs of 'accept all' and 'personalize' buttons in tarteaucitronAlertBig (probably a bug)
2. Renamed "acceptAllCta" since all other parameters uses camelCase.
3. Added a "Deny All" button for the cookie bar in "top" or "bottom" styles. Displayed only if "highPrivacy" is false. Actually "Deny all" is only available for "middle" display.
4. Added condition for "acceptAllCta". If highPrivacy is false and "acceptAllCta" is also false, we should be able to show or hide the button.

## CSS
1. Added SCSS. Made a lof of refactoring over there.
2. Removed some useless and unused reset properties
3. Reworked the CSS by adding CSS variables for easier customisation
4. Changed some colors (green and red) and added some smooth css transitions.

I'm not sure if you're using 2 spaces or 4 spaces for indentation in your JS files but I "beautified" the main script file and the services file (2 spaces).

### CODE REVIEW

**Comment by Manoz** [comment]
Feel free to contact me if you have suggestions or want to discuss about anything. Some changes might be opinionated :)

**Comment by AmauriC** [comment]
Wow, thanks!

I'll start to test asap and come back to you 😃

**Comment by dsoriano** [comment]
Hi, I'm very interested and enthousiactic about this PR but that begs the question of compatibility with old browsers. In the CSS refactor, CSS variables are used. Does it mean that we can drop support of old browsers like IE6-8 ? If yes it's a good news, and I can work on a PR too to clean JS code for old browsers compatibility

**Comment by Manoz** [comment]
Hi, thank you for your feedback.

As I said it's a very opinionated stack and yes by refactoring CSS and using variables I'm somehow dropping IE<11 support.

I'm not sure if it's ok for AmauriC.
In our agency we forked Tarteaucitron and completely dropped IE<11 support everywhere.

I wanted to refactor more JS but it wasn't the scope of this PR. I personally think that CSS variables are awesome for customization.

In our agency we're using Stylelint in every project with solid rules like the one that prohibits the use of hashtags as selector and it's always a pain to disallow those rules in our Tarteaucitron extended CSS files. Now with CSS variables we just have to surcharge the colors :) 

Also, if everything is ok for you, don't merge this PR until I remove the WIP tag 😛 I forgot some stuff

**Comment by AmauriC** [comment]
Hey,

Thanks again for your hard work on this but I'll close this PR, this is too much change and it will break a lot of installations : /

**Pull request closed without merging**
