### PR TITLE
feat: gtag, add hability to declare several domains

### PR DESCRIPTION
**Pull request by JulioJu**
See also 

* https://support.google.com/analytics/answer/7476333?hl=en
* https://developers.google.com/analytics/devguides/collection/gtagjs/cross-domain

### CODE REVIEW

**Comment by JulioJu** [comment]
@AmauriC how to document this on https://tarteaucitron.io/en/install/ ?

**Comment by AmauriC** [comment]
Done ; )

**Comment by JulioJu** [comment]
Thanks @AmauriC .

Note, the current version (1.9.0 or tarteaucitron.js@20210305/) of Tarteaucitron does not embed this change. Therefore the doc is not in accordance with the current release version.

Maybe a new release could be triggered to have a doc and release on same version ?

**Comment by AmauriC** [comment]
A new version will be pushed tomorrow 😊

**Comment by JulioJu** [comment]
Thanks @AmauriC 😄  😄

**Pull request merged**
