### PR TITLE
add Hungarian language

### PR DESCRIPTION
**Pull request by BuyukCem**

### CODE REVIEW

**Comment by BuyukCem** [comment]
Bonjour, 
Désolé de faire beaucoup de petit pull requests, je reçois pas les traductions en même temps

**Comment by pentium10** [comment]
@AmauriC @BuyukCem the contents in the file is not HUNGARIAN language
the contents are for slovak, it was mixed somehow

**Comment by AmauriC** [comment]
😬  can you fix it?

**Comment by BuyukCem** [comment]
Hello, 
Sorry I got feedback from different languages,I confused and made a mistake

**Pull request merged**
